@startuml data-store-container-diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()

SystemDb_Ext(MET_data, "MET Data", "Contains auxiliary MetOcean data (data.met.no).")
SystemDb_Ext(asf, "Alaska SAR Facility", "Contains Sentinel-1 SAR IW mode level-0 data.")

System(sarproc, "SAR Processing Pilot", "SAR processing: Doppler estimation (DCA), additive noise correction of sigma naught (NRCS), image cross-spectra (SCS) estimation. Surface current and wind retrieval.")

System_Boundary(data, "Data Store"){

  ContainerDb(sar_level0, "SAR level-0", "lustre", "All IW mode level-0 data covering the Norwegian coast between 2019-2022.")
  Container(auxdata, "MetOcean data proxy", "Python", "Python tools to perform OGC CSW search for NORA3, NorKyst-800, NorKyst-DS, E39 data and other relevant MetOcean data, and to provide data access via OPeNDAP.")

}

Rel_U(auxdata, sar_level0, "accesses data in", "file")
Rel_U(sarproc, auxdata, "searches and accesses data via", "https")
Rel_U(sar_level0, asf, "copies data from", "https")
Rel_R(auxdata, MET_data, "searches and accesses data in", "https")

@enduml
